"""The currency a country spends, by ISO 3166 country code: so a new trip to "Tokyo"
can suggest JPY without asking. Pure data, no I/O."""

# Countries travellers are likely to visit; others leave the currency to the user.
COUNTRY_CURRENCY: dict[str, str] = {
    # East and South-East Asia
    "JP": "JPY",
    "KR": "KRW",
    "CN": "CNY",
    "HK": "HKD",
    "MO": "MOP",
    "TW": "TWD",
    "SG": "SGD",
    "MY": "MYR",
    "TH": "THB",
    "ID": "IDR",
    "VN": "VND",
    "PH": "PHP",
    "KH": "KHR",
    "LA": "LAK",
    "MM": "MMK",
    "BN": "BND",
    "MN": "MNT",
    # South Asia and the Middle East
    "IN": "INR",
    "LK": "LKR",
    "NP": "NPR",
    "BD": "BDT",
    "MV": "MVR",
    "PK": "PKR",
    "AE": "AED",
    "QA": "QAR",
    "SA": "SAR",
    "OM": "OMR",
    "BH": "BHD",
    "KW": "KWD",
    "JO": "JOD",
    "IL": "ILS",
    "TR": "TRY",
    "EG": "EGP",
    # Oceania
    "AU": "AUD",
    "NZ": "NZD",
    "FJ": "FJD",
    # Europe: the euro area
    "AT": "EUR",
    "BE": "EUR",
    "HR": "EUR",
    "CY": "EUR",
    "EE": "EUR",
    "FI": "EUR",
    "FR": "EUR",
    "DE": "EUR",
    "GR": "EUR",
    "IE": "EUR",
    "IT": "EUR",
    "LV": "EUR",
    "LT": "EUR",
    "LU": "EUR",
    "MT": "EUR",
    "NL": "EUR",
    "PT": "EUR",
    "SK": "EUR",
    "SI": "EUR",
    "ES": "EUR",
    "MC": "EUR",
    "SM": "EUR",
    "VA": "EUR",
    "AD": "EUR",
    "ME": "EUR",
    "XK": "EUR",
    # Europe: other currencies
    "GB": "GBP",
    "CH": "CHF",
    "LI": "CHF",
    "NO": "NOK",
    "SE": "SEK",
    "DK": "DKK",
    "IS": "ISK",
    "PL": "PLN",
    "CZ": "CZK",
    "HU": "HUF",
    "RO": "RON",
    "BG": "BGN",
    "RS": "RSD",
    "BA": "BAM",
    "AL": "ALL",
    "MK": "MKD",
    "GE": "GEL",
    "AM": "AMD",
    "UA": "UAH",
    "MD": "MDL",
    # The Americas
    "US": "USD",
    "CA": "CAD",
    "MX": "MXN",
    "BR": "BRL",
    "AR": "ARS",
    "CL": "CLP",
    "PE": "PEN",
    "CO": "COP",
    "CR": "CRC",
    "PA": "USD",
    "EC": "USD",
    "UY": "UYU",
    "DO": "DOP",
    "JM": "JMD",
    "CU": "CUP",
    "GT": "GTQ",
    "BO": "BOB",
    "PY": "PYG",
    "PR": "USD",
    "BS": "BSD",
    # Africa
    "ZA": "ZAR",
    "MA": "MAD",
    "TN": "TND",
    "KE": "KES",
    "TZ": "TZS",
    "UG": "UGX",
    "RW": "RWF",
    "NG": "NGN",
    "GH": "GHS",
    "MU": "MUR",
    "SC": "SCR",
    "NA": "NAD",
    "BW": "BWP",
    "ET": "ETB",
}


def currency_of(country_code: str | None) -> str | None:
    """The currency spent in the country, or None when it's not one we know."""
    if not country_code:
        return None
    return COUNTRY_CURRENCY.get(country_code.strip().upper())
